config/routes.rb
TallerIntegracion::Application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do

    get "/admin/upload" => "product_reader#index", :as => :admin_import
    post "/admin/upload" => "product_reader#upload"
    post "/admin/upload_file" => "product_reader#upload_file", :as => :admin_import_file
    match '/admin/reports/ingresos' => 'admin/reports#ingresos', :via => [:get, :post], :as =>'ingresos_admin_reports'
    match '/admin/reports/ganancias' => 'admin/reports#ganancias', :via => [:get, :post], :as =>'ganancias_admin_reports'
    match '/admin/reports/bodega_pulmon' => 'admin/reports#bodega_pulmon', :via => [:get, :post], :as =>'bodega_pulmon_admin_reports'
    match '/admin/reports/productos_top' => 'admin/reports#productos_top', :via => [:get, :post], :as =>'productos_top_admin_reports'
    match '/admin/reports/clientes_top' => 'admin/reports#clientes_top', :via => [:get, :post], :as =>'clientes_top_admin_reports'
    match '/admin/reports/transacciones' => 'admin/reports#transacciones', :via => [:get, :post], :as =>'transacciones_admin_reports'
    match '/admin/reports/quiebres_stock' => 'admin/reports#quiebres_stock', :via => [:get, :post], :as =>'quiebres_stock_admin_reports'
    get '/admin/reports/map/:offset' => 'admin/reports#map', :as => 'map'
    get '/admin/reports/map'  => redirect("/admin/reports/map/0"), :as => 'mapa_admin_reports'
    match '/admin/reports/tweets' => 'admin/reports#tweets', :via => [:get, :post], :as =>'tweets_admin_reports'
  end

  scope :path => "/api" do
    get "/disponibles/:username/:password/:sku" => "api#preguntarStock" #Me permite obtener el stock disponible
    post  "/pedirProducto/:username/:password/:sku"  => "api#enviarProducto" #Me permite enviar producto a la bodega dada
  end

end

app/views/spree/admin/reports/bodega_pulmon.html.erb
<%content_for :page_title do%>
	Costo por bodega pulmon del último mes
<%end%>

<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>

<table>
	<tr>
		<td>Cantidad total de producto guardado en el mes</td>
		<td>Costo asociado a bodegaje en bodega pulmon</td>
	</tr>
	<tr>
		<td><%= @total %></td>
		<td><%= @sum %></td>
	</tr>
</table>

app/views/spree/admin/reports/clientes_top.html.erb
<%content_for :page_title do%>
	Clientes VIP
<%end%>

<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>


<h1>Clientes que más han comprado en el último mes</h1>
<table>
	<tr>
		<th>Rut</th>
		<th>Cantidad de transacciones</th>
	</tr>
<% @q.each do |c| %>
	<tr>
		<td><%= c["_id"]%></td>
		<td><%= c["count"]%></td>
	</tr>
<% end %>

app/views/spree/admin/reports/ganancias.html.erb
<%content_for :page_title do%>
	Ganancias del último mes
<%end%>

<%= javascript_include_tag "highstock.js"%>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="container2" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>

$(function () {
        window.chart = new Highcharts.StockChart({
            chart: {
            	renderTo : 'container',
                zoomType: 'x'
            },
            
            title: {
                text: 'Ganancias Diarias'
            },
            yAxis: {
                min: 0,
                title: {
                    text: '$'
                }
            },
            
            rangeSelector: {
            	buttons: [ {
            	type: 'all',
            	text: 'Reset'
            	}],
                enabled: true,
                inputEnabled:false,
            	inputDateFormat: '%d/%m/%Y',
            	inputEditDateFormat: '%d/%m/%Y',
            	
            },
            
            tooltip: {
                shared: true,
                crosshairs: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: <%=raw @series%>
            
        });
        
        $('#container2').highcharts({
            chart: {
                type: 'column',
                zoomType: 'x'
            },
            title: {
                text: 'Ganancias Clientes TOP 10'
            },
            yAxis: {
                min: 0,
                title: {
                    text: '$'
                }
            },
            xAxis: {
                categories: <%=raw @idClientes%>
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: <%=raw @gananciasClientes%>
        });
    });
</script>
<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>

<h1>Resumen</h1>
<h2>Total de utilidades: <b>$ <%= @qqq[:sum]%></b></h2>


<br>
<br><h1>Ganancias por cliente</h1>
<table>
	<tr>
		<td>RUT cliente</td>
		<td>Ganancias</td>
	</tr>
	<tr>
		<% @qq.each do |c|%>
		<td><%= c["_id"] %></td>
		<td><%= c["sum_utilidades"] %></td>
		<% end %>
	</tr>
</table>

app/views/spree/admin/reports/ingresos.html.erb
<%content_for :page_title do%>
	Ingresos del último mes
<%end%>
<%= javascript_include_tag "highstock.js"%>
<%=@q%>
<%=@skuProductos%>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="container2" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="container3" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
$(function () {
        window.chart = new Highcharts.StockChart({
            chart: {
            	renderTo : 'container',
                zoomType: 'x'
            },
            
            title: {
                text: 'Ingresos Diarios'
            },
            yAxis: {
                min: 0,
                title: {
                    text: '$'
                }
            },
            
            rangeSelector: {
            	buttons: [ {
            	type: 'all',
            	text: 'Reset'
            	}],
                enabled: true,
                inputEnabled:false,
            	inputDateFormat: '%d/%m/%Y',
            	inputEditDateFormat: '%d/%m/%Y',
            	
            },
            
            tooltip: {
                shared: true,
                crosshairs: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: <%=raw @series%>
            
        });
        $('#container2').highcharts({
            chart: {
                type: 'column',
                zoomType: 'x'
            },
            title: {
                text: 'Clientes TOP 10'
            },
            xAxis: {
                categories: <%=raw @idClientes%>
            },
            yAxis: {
                min: 0,
                title: {
                    text: '$'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: <%=raw @ingresosClientes%>
        });
    });
</script>
<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>

<h1>Resumen</h1>
<h2>Total de Ingresos: <b>$ <%= @qqq[:sum]%></b></h2>
<br><br>

<br>
<br><h1>Ingresos por cliente</h1>
<table>
	<tr>
		<td>RUT cliente</td>
		<td>Ingresos</td>
	</tr>
	<tr>
		<% @qq.each do |c|%>
		<td><%= c["_id "]%></td>
		<td><%= c["sum_ingresos"] %></td>
		<% end %>
	</tr>
</table>

app/views/spree/admin/reports/map.html.erb
<%content_for :page_title do%>
  Mapa de pedidos
<%end%>

<%content_for :page_actions do%>
  <li><%= link_to_with_icon 'icon-arrow-left','10 anteriores', map_path(offset: params[:offset].to_i+10), :class=>'button' %></li>
  <li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>


<style>
  html, body, #map-canvas {
    height: 370px;
    width: 100%;
    margin: 0px;
    padding: 0px
  }
</style>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script>
  var geocoder;    
  var map;
  var myPedidos = <%=raw @paquetesPedidos.to_json%>;
  var myJSONobject ='{"color":"red","direccion":"ROBERTO DEL RIO  1400 DEPTO 504,PROVIDENCIA,REGION METROPOLITANA","nombreCliente": "Joseto y Julio","pedido": [{"sku": "asdasd","cantidad_enviada": 23,"cantidad_solicitada": 44,"quiebre": true},{"sku": "asdasd","cantidad_enviada": 23,"cantidad_solicitada": 23,"quiebre": true},{"sku": "asdasd","cantidad_enviada": 22,"cantidad_solicitada": 33,"quiebre": false},{"sku": "asdasd","cantidad_enviada": 98,"cantidad_solicitada": 98,"quiebre": false}]}';
  console.log(<%= @h%>)

  function initialize() {
    geocoder = new google.maps.Geocoder();
    var myLatlng = new google.maps.LatLng(-33.426116, -70.598614);
    var mapOptions = {
      zoom: 10,
      center: new google.maps.LatLng(-33.426116, -70.598614)
    };

    map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);

    for(var i in myPedidos)
    {
      codeAddress(JSON.stringify(myPedidos[i]))

    }
  }


  function codeAddress(jsonobject) {

    var json = JSON.parse(jsonobject)
    var address = json.direccion;

    var tabla = parseTable(json)
    error=false;

    geocoder.geocode( { 'address': address}, function(results, status) {

      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        //Ventana a desplegarse cuando se hace click en el marcador
        var infowindow = new google.maps.InfoWindow({
        content: "Cliente: " + json.nombreCliente + "<br />"
                + "Direccion: " + json.direccion + "<br />"
                + "Fecha Limite:" + json.fechaLimite + "<br>" 
                + "Información del Pedido: " + "<br />"
                + tabla
        });
        //Inicializar el marcador
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
        //Declarar el evento para que al hacer click en el marcador se muestre la infowindow
        google.maps.event.addListener(marker, 'click', function() {
          infowindow.open(map,marker);
        });
        //Obtener el icono del mapa desde la url dada por google
        var s1 = 'http://maps.google.com/mapfiles/ms/icons/';
        var s2 = json.color;
        var s3 = '-dot.png'
        var url = s1.concat(s2,s3);
        marker.setIcon(url)
      } else {
        $('#error').html('No se pudieron cargar algunos puntos')
      }
    });
  }

  //Crea una tabla html con los datos de un pedido (para mostrarse en el marcador correspondiente)
  function parseTable(json){
    
    var table = "<table class=\"table.colorful\"><tr><th>SKU</th><th>Cantidad Solicitada</th><th>Cantidad Enviada</th><th>Quiebre</th></tr>"

    for (var i in json.pedido) {
    var counter = json.pedido[i];
    var q ="No";
    if(counter.quiebre)
    {
     // alert(counter.quiebre)
      q = "Si"
    }
     table += "<tr><td><b>" + counter.sku+ "</b></td><td>" + counter.cantidadSolicitada + "</td><td>" + counter.cantidadEnviada + "</td><td>" + q + "</td></tr>";
    } 

    table += "</table>";
    return table
  }

  $(
    function(){
    }
  )
      google.maps.event.addDomListener(window, 'load', initialize);

</script>
<div> <div id="error"></div></div>
    <div id="map-canvas"></div>
</html>

app/views/spree/admin/reports/productos_top.html.erb
<%content_for :page_title do%>
	Productos TOP
<%end%>

<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>

app/views/spree/admin/reports/quiebres_stock.html.erb
<%content_for :page_title do%>
	Quiebres durante el último mes
<%end%>

<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>


<h1>Quiebres de stock desde el último mes</h1>
<h2><%= @total %></h2>

app/views/spree/admin/reports/transacciones.html.erb
<%content_for :page_title do%>
	Transacciones
<%end%>
<%= javascript_include_tag "highstock.js"%>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>
<script>


$(function () {
        window.chart = new Highcharts.StockChart({
            chart: {
            	renderTo : 'container',
                zoomType: 'x'
            },
            tooltip: {
                formatter: function() {return ' ' +
                'Vendido: ' + this.points[0].point.vendido + '<br />' +
                'Quebrado: ' + this.points[0].point.quebrado + '<br />';
            },
                shared: true,
                crosshairs: true,
           },
            title: {
                text: 'Transacciones'
            },
            yAxis: {
                min: 0,
                title: {
                    text: '$'
                }
            },
            
            rangeSelector: {
            	buttons: [ {
            	type: 'all',
            	text: 'Reset'
            	}],
                enabled: true,
                inputEnabled:false,
            	inputDateFormat: '%d/%m/%Y',
            	inputEditDateFormat: '%d/%m/%Y',
            	
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: <%=raw @series%>            
        });
     });
</script>
<h1>Trasacciones realizadas el último mes</h1>
<h2><%= @total %></h2>

app/views/spree/admin/reports/tweets.html.erb
<%content_for :page_title do%>
	Tweets Central Ahorro
<%end%>

<%content_for :page_actions do%>
	<li><%link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class=>'button'%></li>
<%end%>


<h1>Tweets de Central Ahorro</h1>
<a class="twitter-timeline"  href="https://twitter.com/C_Ahorro_G9"  data-widget-id="477957351756951553">Tweets por @C_Ahorro_G9</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>